spring:
  application:
    name: REST API
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://dbserver/testdb
    username: test
    password: test
server:
  port: 8080
